source "https://rubygems.org"
ruby RUBY_VERSION

gem "jekyll", "3.9.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "github-pages", group: :jekyll_plugins
